Class {
	#name : 'ScpInstrumentationHandler',
	#superclass : 'Object',
	#instVars : [
		'instrumentedMethods'
	],
	#category : 'Scopeo-Instrumentation',
	#package : 'Scopeo-Instrumentation'
}

{ #category : 'events handling' }
ScpInstrumentationHandler >> onAssignmentOf: aValue to: aVariable of: anObject [
]

{ #category : 'events handling' }
ScpInstrumentationHandler >> onCallOf: aMethod on: aReceiver from: aSender with: aArguments [

   
]
