Class {
	#name : #ScpInstrumentationHandler,
	#superclass : #Object,
	#category : #'Scopeo-Instrumentation'
}

{ #category : #'events handling' }
ScpInstrumentationHandler >> onAssignment: aVariable of: anObject value: aValue [
]

{ #category : #'events handling' }
ScpInstrumentationHandler >> onMessageSent: aSelector to: aReceiver with: aArguments [
]

{ #category : #'events handling' }
ScpInstrumentationHandler >> onMethodCall: aMethodSelector of: aReceiver from: aSender with: aArguments [

   
]
