Class {
	#name : 'ScpInstrumentationHandler',
	#superclass : 'Object',
	#category : 'Scopeo-Instrumentation',
	#package : 'Scopeo-Instrumentation'
}

{ #category : 'events handling' }
ScpInstrumentationHandler >> onAssignmentOf: aValue to: aVariable of: anObject [
]

{ #category : 'events handling' }
ScpInstrumentationHandler >> onCallOf: aMethodSelector on: aReceiver from: aSender with: aArguments [
]
