Class {
	#name : 'ScpOldTriplet',
	#superclass : 'Object',
	#instVars : [
		'subject',
		'predicate',
		'object'
	],
	#category : 'Scopeo-Model-Deprecated',
	#package : 'Scopeo-Model',
	#tag : 'Deprecated'
}

{ #category : 'accessing' }
ScpOldTriplet >> object [

	^ object
]

{ #category : 'accessing' }
ScpOldTriplet >> object: anObject [

	object := anObject
]

{ #category : 'accessing' }
ScpOldTriplet >> predicate [

	^ predicate
]

{ #category : 'accessing' }
ScpOldTriplet >> predicate: anObject [

	predicate := anObject
]

{ #category : 'accessing' }
ScpOldTriplet >> subject [

	^ subject
]

{ #category : 'accessing' }
ScpOldTriplet >> subject: anObject [

	subject := anObject
]
