Trait {
	#name : #ScpScopeServices,
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'Scopeo-Scope'
}

{ #category : #accessing }
ScpScopeServices >> at: aKey putObject: anObject [

	self explicitRequirement
]

{ #category : #accessing }
ScpScopeServices >> at: aKey putObjectEvent: anObjectEvent [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> at: aKey putObjectEvents: anObjectEventsCollection [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> at: aKey putObjects: anObjectCollection [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> getObjectAt: aKey [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> getObjectEventAt: aKey [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> getObjectEventsAt: aKey [

	self explicitRequirement
]

{ #category : #accessing }
ScpScopeServices >> getObjectEventsKeys [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> getObjectsAt: aKey [

	self explicitRequirement
]

{ #category : #accessing }
ScpScopeServices >> getObjectsKeys [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> removeObjectEventsAt: aKey [

	self explicitRequirement
]

{ #category : #adding }
ScpScopeServices >> removeObjectsAt: aKey [

	self explicitRequirement
]
